"""Stable domain enums with strict rejection of unknown values.

This module holds the cross-cutting, blueprint-stable enumerations that the
domain aggregates reference. Milestone-specific enums (early research
qualification, novelty, engineering workflow, publication, Codex fidelity)
belong to their own milestone files and are intentionally out of scope here.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from synaisthesis.domain.errors import InvalidEnumValueError


class StrictStrEnum(StrEnum):
    """A string-valued enum that rejects unknown values instead of coercing.

    parse is the canonical strict entry point: it returns the member for a known
    value and raises InvalidEnumValueError otherwise. Direct construction such
    as StageId("S9") is also strict and raises ValueError for unknown values.
    """

    @classmethod
    def parse(cls, value: Any, *, field: str = "value") -> StrictStrEnum:
        if isinstance(value, cls):
            return value
        try:
            return cls(value)
        except ValueError as exc:
            allowed = [member.value for member in cls]
            raise InvalidEnumValueError(field=field, value=value, allowed=allowed) from exc


class StageId(StrictStrEnum):
    """Incubator stage identifiers S0-S10 (blueprint 03)."""

    S0 = "S0"
    S1 = "S1"
    S2 = "S2"
    S3 = "S3"
    S4 = "S4"
    S5 = "S5"
    S6 = "S6"
    S7 = "S7"
    S8 = "S8"
    S9 = "S9"
    S10 = "S10"


class ProgressKind(StrictStrEnum):
    """Kinds of substantive incubator progress (blueprint 03, section 2)."""

    DEFINITION = "DEFINITION"
    BOUNDARY = "BOUNDARY"
    MECHANISM = "MECHANISM"
    EVIDENCE = "EVIDENCE"
    TEST = "TEST"
    ASSUMPTION = "ASSUMPTION"
    FORMALIZATION = "FORMALIZATION"
    COUNTEREXAMPLE = "COUNTEREXAMPLE"
    HANDOFF = "HANDOFF"


class StageGateStatus(StrictStrEnum):
    """Result of a stage gate evaluation (blueprint 03 section 3, 07 section 2)."""

    PASS = "PASS"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    NOT_TESTED = "NOT_TESTED"


class ProjectLifecycleStatus(StrictStrEnum):
    """Project lifecycle states (blueprint 06, section 2)."""

    SEED = "SEED"
    INCUBATING = "INCUBATING"
    NATURAL_LANGUAGE_DESIGN_READY = "NATURAL_LANGUAGE_DESIGN_READY"
    EARLY_RESEARCH_QUALIFYING = "EARLY_RESEARCH_QUALIFYING"
    FORMALIZATION_FEASIBILITY_REVIEWING = "FORMALIZATION_FEASIBILITY_REVIEWING"
    THEORY_OR_HYBRID_ROUTE = "THEORY_OR_HYBRID_ROUTE"
    FORMALIZATION_CANDIDATE = "FORMALIZATION_CANDIDATE"
    FORMALIZATION_USER_REVIEW = "FORMALIZATION_USER_REVIEW"
    NOVELTY_REVIEWING = "NOVELTY_REVIEWING"
    NOVELTY_QUALIFIED = "NOVELTY_QUALIFIED"
    BLOCKED_NOVELTY_USER = "BLOCKED_NOVELTY_USER"
    MATURE_IDEA_READY = "MATURE_IDEA_READY"
    THEORY_BUILDING = "THEORY_BUILDING"
    CLAIM_COMPILED = "CLAIM_COMPILED"
    CLAIM_FROZEN = "CLAIM_FROZEN"
    COUNCIL_RUNNING = "COUNCIL_RUNNING"
    CANDIDATE_STABLE = "CANDIDATE_STABLE"
    THEORY_MASTER_MANUSCRIPT_BUILDING = "THEORY_MASTER_MANUSCRIPT_BUILDING"
    THEORY_MASTER_MANUSCRIPT_AUDITING = "THEORY_MASTER_MANUSCRIPT_AUDITING"
    THEORY_MASTER_MANUSCRIPT_READY = "THEORY_MASTER_MANUSCRIPT_READY"
    FORMAL_MANUSCRIPT_DECISION_REQUIRED = "FORMAL_MANUSCRIPT_DECISION_REQUIRED"
    MASTER_ONLY_DELIVERED = "MASTER_ONLY_DELIVERED"
    MASTER_REVISION_REQUIRED = "MASTER_REVISION_REQUIRED"
    FORMAL_MANUSCRIPT_PAUSED = "FORMAL_MANUSCRIPT_PAUSED"
    PUBLICATION_PROFILE_REQUIRED = "PUBLICATION_PROFILE_REQUIRED"
    FORMAL_MANUSCRIPT_READY = "FORMAL_MANUSCRIPT_READY"
    ARXIV_PACKAGE_READY = "ARXIV_PACKAGE_READY"
    ENGINEERING_ROUTE_USER_DECISION = "ENGINEERING_ROUTE_USER_DECISION"
    ENGINEERING_CONCEPT_CANDIDATE = "ENGINEERING_CONCEPT_CANDIDATE"
    ENGINEERING_CONCEPT_USER_REVIEW = "ENGINEERING_CONCEPT_USER_REVIEW"
    ENGINEERING_NOVELTY_REVIEWING = "ENGINEERING_NOVELTY_REVIEWING"
    ENGINEERING_NOVELTY_QUALIFIED = "ENGINEERING_NOVELTY_QUALIFIED"
    ENGINEERING_DESIGNING = "ENGINEERING_DESIGNING"
    ENGINEERING_ARCHITECTURE_REVIEW = "ENGINEERING_ARCHITECTURE_REVIEW"
    ENGINEERING_BLUEPRINTING = "ENGINEERING_BLUEPRINTING"
    ENGINEERING_VALIDATING = "ENGINEERING_VALIDATING"
    ENGINEERING_PUBLISHING = "ENGINEERING_PUBLISHING"
    ENGINEERING_DELIVERY_READY = "ENGINEERING_DELIVERY_READY"
    FORMALIZATION_FEASIBILITY_USER_DECISION = "FORMALIZATION_FEASIBILITY_USER_DECISION"
    BLOCKED_HUMAN = "BLOCKED_HUMAN"
    BLOCKED_TOOL = "BLOCKED_TOOL"
    USER_ACCEPTED = "USER_ACCEPTED"
    REVOKED = "REVOKED"


class ProvenanceType(StrictStrEnum):
    """Origin of a piece of data (blueprint 06, section 3)."""

    USER_INPUT = "USER_INPUT"
    USER_DECISION = "USER_DECISION"
    EXTERNAL_MODEL_IMPORT = "EXTERNAL_MODEL_IMPORT"
    EXTERNAL_SOURCE = "EXTERNAL_SOURCE"
    ASSISTANT_PROPOSAL = "ASSISTANT_PROPOSAL"
    DERIVED = "DERIVED"
    TOOL_EXECUTION = "TOOL_EXECUTION"
    CODEX_EXECUTION = "CODEX_EXECUTION"
    HUMAN_VERIFIED = "HUMAN_VERIFIED"


class EvidenceType(StrictStrEnum):
    """Kinds of evidence (blueprint 06, section 4)."""

    LITERATURE_METADATA = "LITERATURE_METADATA"
    LITERATURE_INTERPRETATION = "LITERATURE_INTERPRETATION"
    PRIOR_ART_METADATA_VERIFIED = "PRIOR_ART_METADATA_VERIFIED"
    ENGINEERING_MATURITY_EVIDENCE = "ENGINEERING_MATURITY_EVIDENCE"
    FORMALIZATION_FEASIBILITY_ASSESSMENT = "FORMALIZATION_FEASIBILITY_ASSESSMENT"
    EARLY_FORMALIZATION_ALIGNMENT = "EARLY_FORMALIZATION_ALIGNMENT"
    ENGINEERING_CONCEPT_ALIGNMENT = "ENGINEERING_CONCEPT_ALIGNMENT"
    NOVELTY_SCORECARD = "NOVELTY_SCORECARD"
    REQUIREMENTS_BASELINE = "REQUIREMENTS_BASELINE"
    ARCHITECTURE_BASELINE = "ARCHITECTURE_BASELINE"
    ENGINEERING_TRACEABILITY = "ENGINEERING_TRACEABILITY"
    VERIFICATION_REPORT = "VERIFICATION_REPORT"
    VALIDATION_REPORT = "VALIDATION_REPORT"
    MANUSCRIPT_CLAIM_EVIDENCE = "MANUSCRIPT_CLAIM_EVIDENCE"
    VENUE_COMPLIANCE_MATRIX = "VENUE_COMPLIANCE_MATRIX"
    COUNTEREXAMPLE = "COUNTEREXAMPLE"
    SMT_MODEL = "SMT_MODEL"
    SMT_UNSAT_WITHIN_ENCODING = "SMT_UNSAT_WITHIN_ENCODING"
    PYTHON_EXPERIMENT = "PYTHON_EXPERIMENT"
    LEAN_KERNEL_ACCEPTED = "LEAN_KERNEL_ACCEPTED"
    LEAN_ERROR = "LEAN_ERROR"
    CODEX_EXECUTION_RECEIPT = "CODEX_EXECUTION_RECEIPT"
    SEMANTIC_AUDIT = "SEMANTIC_AUDIT"
    REGRESSION_RESULT = "REGRESSION_RESULT"
    HUMAN_CONFIRMATION = "HUMAN_CONFIRMATION"
    CONSTRUCTION_ARTIFACT = "CONSTRUCTION_ARTIFACT"


class EvidenceStatus(StrictStrEnum):
    """Lifecycle state of evidence (blueprint 06, section 1, evidence.status)."""

    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class EvidenceStrength(StrictStrEnum):
    """Evidence strength tiers E0-E5 (blueprint 06, section 5)."""

    E0 = "E0"
    E1 = "E1"
    E2 = "E2"
    E3 = "E3"
    E4 = "E4"
    E5 = "E5"


class IndependenceStatus(StrictStrEnum):
    """Independence status of a verification (blueprint 06, section 6)."""

    INDEPENDENT_VERIFIED = "INDEPENDENT_VERIFIED"
    INDEPENDENT_PARTIAL = "INDEPENDENT_PARTIAL"
    SAME_MODEL_FAMILY = "SAME_MODEL_FAMILY"
    CONTEXT_LEAK_SUSPECTED = "CONTEXT_LEAK_SUSPECTED"
    ISOLATION_VIOLATION = "ISOLATION_VIOLATION"
    NOT_APPLICABLE = "NOT_APPLICABLE"
